### PR TITLE
remove kind errors

### PR DESCRIPTION
**Pull request by Mackiovello**
Kinds no longer exists in Starcounter, so it should be safe to remove the errors. 

This has to be merged after #28 for the version increment correctly.

### CODE REVIEW

**Comment by k-rus** [comment]
There was a policy that error codes are never removed, but commented out instead. The reason for the policy is that if the error code was ever used, removing it can allow to add it again but with different meaning, which might be confusing. I don't know if it is applicable here.

**Comment by chrhol** [comment]
Yes, @k-rus is correct, or at least we haven't explicitly said anything else about it :). Can you change so that you comment out the codes instead and leave them in the file?

**Comment by Mackiovello** [comment]
Now they're commented out instead of deleted. I messed up the commit message, but I'll leave that be. If this is alright, I'll change the version to 0.14 and merge with master.

**Comment by chrhol** [comment]
I did a quick search and it seems that one place in the weaver still uses these codes (or at least references them): https://github.com/Starcounter/level1/blob/develop/src/Starcounter.Weaver/Starcounter.Internal.Weaver/WeaverUtilities.cs#L131-L147

Not sure if this is just something that have been left in the code, or if it's something that is actually used, but it will mean that with this change, Level1 needs to be updated as well.

**Comment by chrhol** [comment]
On a sidenote of this, I really need to do this: #25 or if it's possible (not sure how though) to be able to make a personal build in teamcity using a non-published nuget to make sure builds succeeds.

**Comment by Mackiovello** [comment]
Thank you for the investigation. Let's not spend too much time on this then. I'm closing the PR if you don't believe that this should be fixed immediately.

**Comment by chrhol** [comment]
Yeah lets do that this time. Long-term we probably need to come up with some guidelines and simplifications on how to maintain errorcodes.

**Pull request closed without merging**
